services:
  postgres:
    image: postgres:15-alpine
    container_name: assimilate-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ${DB_DATA_DIR}:/var/lib/postgresql/data
      - ${DB_INIT}:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"